-keepnames class android.graphics.Rect
-keepnames class android.net.Uri
-keepnames class android.net.Uri
-keepnames class soup.nolan.ui.camera.CameraFragment
-keepnames class soup.nolan.ui.edit.PhotoEditFragment
-keepnames class soup.nolan.ui.edit.crop.PhotoEditCropFragment
-keepnames class soup.nolan.ui.settings.SettingsFragment
-keepnames class soup.nolan.ui.splash.SplashFragment